"""
File: health_issues.py
Description: Defines the HealthIssues class used to record and describe individual
medical concerns detected in animals. Each instance includes a description, date
reported, severity level, and treatment plan. This class provides formatted
summaries suitable for inclusion in full health reports generated by the Zoo
Management System.
Author: Shaune Legayada
ID: 110444251
Username: legsd001
This is my own work as defined by the University's Academic Integrity Policy.
"""

class HealthIssues:
    """
    Represents a single health issue associated with an animal.

    Attributes:
        __description (str): Text describing the health concern.
        __date_reported (str): The date the issue was observed.
        __severity (str): Severity level (Low, Medium, High, Critical).
        __treatment_plan (str): Recommended treatment approach.
    """

    SEVERITY_LEVELS = {"Low", "Medium", "High", "Critical"}

    def __init__(self, description, date_reported, severity, treatment_plan):
        """Initialise a HealthIssue instance."""
        self.__description = description
        self.__date_reported = date_reported
        self.__severity = severity
        self.__treatment_plan = treatment_plan

    # -------------------- Properties --------------------

    def get_description(self):
        """Return the issue description."""
        return self.__description

    def get_date_reported(self):
        """Return the report date."""
        return self.__date_reported

    def get_severity(self):
        """Return the severity level."""
        return self.__severity

    def get_treatment_plan(self):
        """Return the treatment plan."""
        return self.__treatment_plan

    description = property(get_description)
    date_reported = property(get_date_reported)
    severity = property(get_severity)
    treatment_plan = property(get_treatment_plan)

    # -------------------- Formatting --------------------

    def summarise_issue(self):
        """
        Return a formatted multi-line summary of the health issue.

        Used by HealthRecords.generate_report() to produce complete animal
        medical histories.
        """
        return (f"Description: {self.__description}\n"
            f"Date: {self.__date_reported}\n"
            f"Severity: {self.__severity}\n"
            f"Treatment: {self.__treatment_plan}"
        )
